# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

language: clojure
lein: lein2
script: lein2 sub with-profile dev,provided test
before_install:
    - lein2 sub install
branches:
  only:
    - develop
    - master
jdk:
  - openjdk6
notifications:
  email:
    - timbers@ualberta.ca
